# Generated by Django 4.0.3 on 2024-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0004_alter_sub_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ins',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='ins',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='ins',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ins',
            name='address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='ins',
            name='phone',
            field=models.CharField(default='0000000', max_length=15),
        ),
        migrations.AddField(
            model_name='ins',
            name='station_id',
            field=models.CharField(default='1', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='ins',
            name='station_name',
            field=models.CharField(default='none', max_length=30, unique=True),
        ),
    ]
