# Generated by Django 4.0.3 on 2024-04-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0005_remove_ins_fname_remove_ins_lname_remove_ins_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('distinguishing_features', models.TextField()),
                ('offenses_committed', models.TextField()),
                ('last_known_location', models.CharField(max_length=100)),
                ('rewards_offered', models.CharField(blank=True, max_length=100)),
                ('recent_photographs', models.ImageField(upload_to='most_wanted_photos/')),
                ('contact_numbers', models.CharField(max_length=100)),
                ('background_information', models.TextField(blank=True)),
                ('known_addresses', models.TextField(blank=True)),
                ('date_of_last_known_activity', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(max_length=50)),
            ],
        ),
    ]
