# Generated by Django 4.0.3 on 2024-04-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
