# Generated by Django 4.0.3 on 2024-04-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0005_remove_ins_fname_remove_ins_lname_remove_ins_user_id_and_more'),
        ('myapp', '0018_missing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inspector.ins'),
        ),
    ]
