# Generated by Django 4.0.3 on 2024-04-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspector', '0006_mostwanted'),
        ('myapp', '0019_alter_fir_police'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inspector.ins'),
        ),
    ]
